version: '3.8'

networks:
  evo:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - evo
    volumes:
      - ./src:/var/www/evo
      - ./docker/configs/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: docker/images/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/evo
    networks:
      - evo

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - evo
    volumes:
      - ./docker/db:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8008:8080
  #   networks:
  #     - evo
  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - evo
